# Generated by Django 3.0.4 on 2020-03-06 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('proposito', models.CharField(max_length=50)),
                ('fecha_realizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=50)),
                ('urlFoto', models.CharField(max_length=50)),
            ],
        ),
    ]
