# Generated by Django 3.0.4 on 2020-03-06 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta conversacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'conversacion',
                'verbose_name_plural': 'conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text='Mensaje del cliente', max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(help_text='Respuesta del servidor', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='palabrasClave',
            fields=[
                ('idrespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(blank=True, choices=[('c', 'Cliente'), ('s', 'Servidor')], default='c', help_text='EMISOR', max_length=1)),
                ('conversacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.Conversacion')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
            },
        ),
    ]
