# Generated by Django 3.0.4 on 2020-03-07 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabrasclave',
            name='palabrasClave',
            field=models.AutoField(default=uuid.uuid4, help_text='ID único para esta palabra clave', primary_key=True, serialize=False),
        ),
    ]
