# Generated by Django 3.0.4 on 2020-03-07 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_palabrasclave_palabra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palabrasclave',
            name='idrespuesta',
        ),
        migrations.AddField(
            model_name='palabrasclave',
            name='idpregunta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='idrespuesta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Respuesta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.AutoField(default=uuid.uuid4, help_text='ID único para esta palabra clave', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(default=uuid.uuid4, help_text='ID único para esta palabra clave', primary_key=True, serialize=False),
        ),
    ]
