# Generated by Django 3.0.4 on 2020-03-06 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('costo', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descuento', models.BooleanField()),
                ('procentaje_descuento', models.BigIntegerField()),
                ('urlFoto', models.CharField(max_length=50)),
            ],
        ),
    ]
