# Generated by Django 3.0.4 on 2020-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
